package com.fidelis.syncbatch.agent.model;

import java.time.Instant;

/**
 * A comment generated by the intelligent monitoring agent.
 */
public record AgentComment(
        String icon,
        String text,
        Severity severity,
        String context,
        Instant timestamp
) {
    public enum Severity { SUCCESS, INFO, WARNING, ERROR }

    public static AgentComment success(String icon, String text, String context) {
        return new AgentComment(icon, text, Severity.SUCCESS, context, Instant.now());
    }

    public static AgentComment info(String icon, String text, String context) {
        return new AgentComment(icon, text, Severity.INFO, context, Instant.now());
    }

    public static AgentComment warning(String icon, String text, String context) {
        return new AgentComment(icon, text, Severity.WARNING, context, Instant.now());
    }

    public static AgentComment error(String icon, String text, String context) {
        return new AgentComment(icon, text, Severity.ERROR, context, Instant.now());
    }
}
